var constants = {
	ADD_VIDEO: "ADD_VIDEO",
	ADD_VIDEO_TOP: "ADD_VIDEO_TOP",
	MOVE_VIDEO: "MOVE_VIDEO",
	REMOVE_VIDEO: "REMOVE_VIDEO",
	CLEAR_VIDEOS: "CLEAR_VIDEOS",
	PLAY_VIDEO_ID: "PLAY_VIDEO_ID",
	PLAY_NEXT: "PLAY_NEXT",
	HYDRATE: "HYDRATE"
};

module.exports = constants;